### ISSUE TITLE
error on setup: "coError: Cannot find module './config'" 

### ISSUE THREAD

**Issue by tesla809** [jun-sung/doge-emporium#1]
While following instructions in `README.MD` I encounter errors:

`coError: Cannot find module './config'`

I suspect the issue is a global variable. Like `./config` is installed in npm as -g.
Please check your globals.

**Comment by jun-sung** [comment]
I placed config.js in .gitignore (instead of putting sensitive info in .env as seen [here](https://blog.infura.io/ethereum-javascript-libraries-web3-js-vs-ethers-js-part-ii)). To my understanding, I'm not to push this file and make it public.

**Comment by tesla809** [comment]
It would be better to 
1. place sensitive information in the .env file. 
2. Then place the .env file in the .gitignore. 
3. Remove .config from .gitignore
4. push .config (making sure no sensitive information only in .env and imported via a variable to .config)

That way there is a nice separation of concerns between sensitive information and setup information.

This approach also makes it easier to get the project started. The user booting up the project would only have:
1. create a .env file
2. Add a few bits of information
3. Vioala! Done

A dev without web3 experience would be able to do that, versus having to understand what Truffle is, how to work it, etc. Ideally, you want to make your project as easy as possible to set up and interact with.

Would you be able to update and push?

Here is some info on dotenv:
https://www.npmjs.com/package/dotenv

Hope this helps

**Comment by jun-sung** [comment]
Hey Anthony, thank you for clarifying!
I’m working on polishing up my README.md, but wanted to ask if you could check something on your end:

After I moved the Infura Project ID and Mnemonic to .env file, I had an issue where my package-lock.json and node_modules directory were causing trouble when I ran `npm run dev` because they were misrouted into looking for the old nonexistent config.js file.

So I deleted package-lock.json and node_modules and then `npm run dev` started to work again.

When you clone this repo on your end and run through the directions on README.md, does it work? If not, where does it stop working? I'm thinking I'll have to delete node_modules and package-lock.json from the repo.

**Comment by jun-sung** [comment]
I updated the dependencies and ran through installation and interacting on a local server via a different computer. Everything should be working now. Please let me know if you run into any further issues!
