### ISSUE TITLE
missed chance to use Ownable.sol

### ISSUE THREAD

**Issue by tesla809** [jun-sung/doge-emporium#4]
Instead of 
 ```
 // @return if msg.sender is admin.
    function isAdmin() public view returns(bool) {
        return _admin == msg.sender;
    }
```
You can turn it into a function modifer
or better yet import Openzeppelin's `Ownable.sol` and use the function modifer `onlyOwner`.

**Comment by jun-sung** [comment]
I'd love to incorporate your suggestion, but I've been unable to import and utilize Ownable.sol in my contract! I followed the example [Exchange.sol for Fojini-DEX](https://github.com/MatricksDeCoder/Fojini-DEX/blob/master/src/contracts/Exchange.sol) where he's using it successfully. I've tried various npm installs and version changes, but to no success.

Here's what my contract looks like when attempting to import Ownable.sol:
```
pragma solidity ^0.5.0;

import "@openzeppelin/contracts/math/SafeMath.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract Purchase is Ownable {

    using SafeMath for uint;
```

And then the following error message when attempting to compile via Truffle:
```Bash
junsung@juns-mbp doge-emporium % truffle compile

Compiling your contracts...
===========================
Error: Could not find @openzeppelin/contracts/access/Ownable.sol from any sources; imported from /Users/junsung/dev/ConsenSys/doge-emporium/contracts/Purchase.sol
    at Resolver.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:62:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:5:42)
Truffle v5.1.58 (core: 5.1.58)
Node v12.18.4
```
Here are some places where I was looking for the answer:
https://forum.openzeppelin.com/t/could-not-find-ownable-sol-file-openzeppelin-contracts-access-ownable-sol/3685
> _One solution that works for me until this will be fixed is to add also the node_modules folder to the relative path (after I installed the package locally of course :) ).
For example, instead of import 'zeppelin-solidity/contracts/token/MintableToken.sol'
I did: import '../../node_modules/zeppelin-solidity/contracts/token/MintableToken.sol'
I resolved the same problem with: npm init
so now the sequence is:
npm init
truffle init
npm install zeppelin-solidity
truffle compile
hope it would helps
npm install zeppelin-solidity_

**What are your thoughts?**

**Comment by jun-sung** [comment]
Copy/pasted Ownable.sol locally and imported from there.
